### PR TITLE
(Chore) Terraform v0.12 update

### PR DESCRIPTION
**Pull request by Stretch96**
* Fixes 0.12 syntax errors

### CODE REVIEW

**Comment by Stretch96** [comment]
WIP - Will let you know when it's y to be merged in 😬

**Comment by Stretch96** [comment]
It's ready to go now 👍

**Comment by andreynpetrov** [comment]
I merged commit. Sorry for delay.

**Comment by andreynpetrov** [comment]
It's version v0.9 now.

**Comment by Stretch96** [comment]
Cool thanks 👍

**Pull request merged**
